#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentist_Project.DXL_LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dentist_DB")]
	public partial class CLS_DXL_IINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Patient(Table_Patient instance);
    partial void UpdateTable_Patient(Table_Patient instance);
    partial void DeleteTable_Patient(Table_Patient instance);
    partial void InsertTable_Expence(Table_Expence instance);
    partial void UpdateTable_Expence(Table_Expence instance);
    partial void DeleteTable_Expence(Table_Expence instance);
    partial void InsertTable_User_Permission(Table_User_Permission instance);
    partial void UpdateTable_User_Permission(Table_User_Permission instance);
    partial void DeleteTable_User_Permission(Table_User_Permission instance);
    #endregion
		
		public CLS_DXL_IINQDataContext() : 
				base(global::Dentist_Project.Properties.Settings.Default.Dentist_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_DXL_IINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_DXL_IINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_DXL_IINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_DXL_IINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Patient> Table_Patients
		{
			get
			{
				return this.GetTable<Table_Patient>();
			}
		}
		
		public System.Data.Linq.Table<Table_Expence> Table_Expences
		{
			get
			{
				return this.GetTable<Table_Expence>();
			}
		}
		
		public System.Data.Linq.Table<Table_User_Permission> Table_User_Permissions
		{
			get
			{
				return this.GetTable<Table_User_Permission>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Patients")]
	public partial class Table_Patient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Patient_id;
		
		private string _Patient_tc;
		
		private string _Patient_name;
		
		private int _Patient_age;
		
		private string _Patient_gender;
		
		private string _Patient_phone;
		
		private System.DateTime _Patient_date;
		
		private string _Patient_email;
		
		private double _cost;
		
		private double _paied;
		
		private double _remind;
		
		private System.Data.Linq.Binary _Patient_img;
		
		private string _Patient_state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatient_idChanging(int value);
    partial void OnPatient_idChanged();
    partial void OnPatient_tcChanging(string value);
    partial void OnPatient_tcChanged();
    partial void OnPatient_nameChanging(string value);
    partial void OnPatient_nameChanged();
    partial void OnPatient_ageChanging(int value);
    partial void OnPatient_ageChanged();
    partial void OnPatient_genderChanging(string value);
    partial void OnPatient_genderChanged();
    partial void OnPatient_phoneChanging(string value);
    partial void OnPatient_phoneChanged();
    partial void OnPatient_dateChanging(System.DateTime value);
    partial void OnPatient_dateChanged();
    partial void OnPatient_emailChanging(string value);
    partial void OnPatient_emailChanged();
    partial void OncostChanging(double value);
    partial void OncostChanged();
    partial void OnpaiedChanging(double value);
    partial void OnpaiedChanged();
    partial void OnremindChanging(double value);
    partial void OnremindChanged();
    partial void OnPatient_imgChanging(System.Data.Linq.Binary value);
    partial void OnPatient_imgChanged();
    partial void OnPatient_stateChanging(string value);
    partial void OnPatient_stateChanged();
    #endregion
		
		public Table_Patient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Patient_id
		{
			get
			{
				return this._Patient_id;
			}
			set
			{
				if ((this._Patient_id != value))
				{
					this.OnPatient_idChanging(value);
					this.SendPropertyChanging();
					this._Patient_id = value;
					this.SendPropertyChanged("Patient_id");
					this.OnPatient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_tc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_tc
		{
			get
			{
				return this._Patient_tc;
			}
			set
			{
				if ((this._Patient_tc != value))
				{
					this.OnPatient_tcChanging(value);
					this.SendPropertyChanging();
					this._Patient_tc = value;
					this.SendPropertyChanged("Patient_tc");
					this.OnPatient_tcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_name
		{
			get
			{
				return this._Patient_name;
			}
			set
			{
				if ((this._Patient_name != value))
				{
					this.OnPatient_nameChanging(value);
					this.SendPropertyChanging();
					this._Patient_name = value;
					this.SendPropertyChanged("Patient_name");
					this.OnPatient_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_age", DbType="Int NOT NULL")]
		public int Patient_age
		{
			get
			{
				return this._Patient_age;
			}
			set
			{
				if ((this._Patient_age != value))
				{
					this.OnPatient_ageChanging(value);
					this.SendPropertyChanging();
					this._Patient_age = value;
					this.SendPropertyChanged("Patient_age");
					this.OnPatient_ageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_gender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_gender
		{
			get
			{
				return this._Patient_gender;
			}
			set
			{
				if ((this._Patient_gender != value))
				{
					this.OnPatient_genderChanging(value);
					this.SendPropertyChanging();
					this._Patient_gender = value;
					this.SendPropertyChanged("Patient_gender");
					this.OnPatient_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_phone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_phone
		{
			get
			{
				return this._Patient_phone;
			}
			set
			{
				if ((this._Patient_phone != value))
				{
					this.OnPatient_phoneChanging(value);
					this.SendPropertyChanging();
					this._Patient_phone = value;
					this.SendPropertyChanged("Patient_phone");
					this.OnPatient_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_date", DbType="Date NOT NULL")]
		public System.DateTime Patient_date
		{
			get
			{
				return this._Patient_date;
			}
			set
			{
				if ((this._Patient_date != value))
				{
					this.OnPatient_dateChanging(value);
					this.SendPropertyChanging();
					this._Patient_date = value;
					this.SendPropertyChanged("Patient_date");
					this.OnPatient_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_email
		{
			get
			{
				return this._Patient_email;
			}
			set
			{
				if ((this._Patient_email != value))
				{
					this.OnPatient_emailChanging(value);
					this.SendPropertyChanging();
					this._Patient_email = value;
					this.SendPropertyChanged("Patient_email");
					this.OnPatient_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost", DbType="Float NOT NULL")]
		public double cost
		{
			get
			{
				return this._cost;
			}
			set
			{
				if ((this._cost != value))
				{
					this.OncostChanging(value);
					this.SendPropertyChanging();
					this._cost = value;
					this.SendPropertyChanged("cost");
					this.OncostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paied", DbType="Float NOT NULL")]
		public double paied
		{
			get
			{
				return this._paied;
			}
			set
			{
				if ((this._paied != value))
				{
					this.OnpaiedChanging(value);
					this.SendPropertyChanging();
					this._paied = value;
					this.SendPropertyChanged("paied");
					this.OnpaiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remind", DbType="Float NOT NULL")]
		public double remind
		{
			get
			{
				return this._remind;
			}
			set
			{
				if ((this._remind != value))
				{
					this.OnremindChanging(value);
					this.SendPropertyChanging();
					this._remind = value;
					this.SendPropertyChanged("remind");
					this.OnremindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Patient_img
		{
			get
			{
				return this._Patient_img;
			}
			set
			{
				if ((this._Patient_img != value))
				{
					this.OnPatient_imgChanging(value);
					this.SendPropertyChanging();
					this._Patient_img = value;
					this.SendPropertyChanged("Patient_img");
					this.OnPatient_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_state", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_state
		{
			get
			{
				return this._Patient_state;
			}
			set
			{
				if ((this._Patient_state != value))
				{
					this.OnPatient_stateChanging(value);
					this.SendPropertyChanging();
					this._Patient_state = value;
					this.SendPropertyChanged("Patient_state");
					this.OnPatient_stateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Expences")]
	public partial class Table_Expence : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Expences_id;
		
		private string _Expences_No;
		
		private double _Expences_value;
		
		private string _Expences_Name;
		
		private System.DateTime _Expences_Date;
		
		private string _Expences_Note;
		
		private string _Expences_FileName;
		
		private System.Data.Linq.Binary _Expences_Attachment;
		
		private string _Expences_File_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExpences_idChanging(int value);
    partial void OnExpences_idChanged();
    partial void OnExpences_NoChanging(string value);
    partial void OnExpences_NoChanged();
    partial void OnExpences_valueChanging(double value);
    partial void OnExpences_valueChanged();
    partial void OnExpences_NameChanging(string value);
    partial void OnExpences_NameChanged();
    partial void OnExpences_DateChanging(System.DateTime value);
    partial void OnExpences_DateChanged();
    partial void OnExpences_NoteChanging(string value);
    partial void OnExpences_NoteChanged();
    partial void OnExpences_FileNameChanging(string value);
    partial void OnExpences_FileNameChanged();
    partial void OnExpences_AttachmentChanging(System.Data.Linq.Binary value);
    partial void OnExpences_AttachmentChanged();
    partial void OnExpences_File_TypeChanging(string value);
    partial void OnExpences_File_TypeChanged();
    #endregion
		
		public Table_Expence()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Expences_id
		{
			get
			{
				return this._Expences_id;
			}
			set
			{
				if ((this._Expences_id != value))
				{
					this.OnExpences_idChanging(value);
					this.SendPropertyChanging();
					this._Expences_id = value;
					this.SendPropertyChanged("Expences_id");
					this.OnExpences_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_No", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Expences_No
		{
			get
			{
				return this._Expences_No;
			}
			set
			{
				if ((this._Expences_No != value))
				{
					this.OnExpences_NoChanging(value);
					this.SendPropertyChanging();
					this._Expences_No = value;
					this.SendPropertyChanged("Expences_No");
					this.OnExpences_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_value", DbType="Float NOT NULL")]
		public double Expences_value
		{
			get
			{
				return this._Expences_value;
			}
			set
			{
				if ((this._Expences_value != value))
				{
					this.OnExpences_valueChanging(value);
					this.SendPropertyChanging();
					this._Expences_value = value;
					this.SendPropertyChanged("Expences_value");
					this.OnExpences_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Expences_Name
		{
			get
			{
				return this._Expences_Name;
			}
			set
			{
				if ((this._Expences_Name != value))
				{
					this.OnExpences_NameChanging(value);
					this.SendPropertyChanging();
					this._Expences_Name = value;
					this.SendPropertyChanged("Expences_Name");
					this.OnExpences_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Expences_Date
		{
			get
			{
				return this._Expences_Date;
			}
			set
			{
				if ((this._Expences_Date != value))
				{
					this.OnExpences_DateChanging(value);
					this.SendPropertyChanging();
					this._Expences_Date = value;
					this.SendPropertyChanged("Expences_Date");
					this.OnExpences_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_Note", DbType="NVarChar(MAX)")]
		public string Expences_Note
		{
			get
			{
				return this._Expences_Note;
			}
			set
			{
				if ((this._Expences_Note != value))
				{
					this.OnExpences_NoteChanging(value);
					this.SendPropertyChanging();
					this._Expences_Note = value;
					this.SendPropertyChanged("Expences_Note");
					this.OnExpences_NoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_FileName", DbType="NVarChar(MAX)")]
		public string Expences_FileName
		{
			get
			{
				return this._Expences_FileName;
			}
			set
			{
				if ((this._Expences_FileName != value))
				{
					this.OnExpences_FileNameChanging(value);
					this.SendPropertyChanging();
					this._Expences_FileName = value;
					this.SendPropertyChanged("Expences_FileName");
					this.OnExpences_FileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_Attachment", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Expences_Attachment
		{
			get
			{
				return this._Expences_Attachment;
			}
			set
			{
				if ((this._Expences_Attachment != value))
				{
					this.OnExpences_AttachmentChanging(value);
					this.SendPropertyChanging();
					this._Expences_Attachment = value;
					this.SendPropertyChanged("Expences_Attachment");
					this.OnExpences_AttachmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expences_File_Type", DbType="NChar(10)")]
		public string Expences_File_Type
		{
			get
			{
				return this._Expences_File_Type;
			}
			set
			{
				if ((this._Expences_File_Type != value))
				{
					this.OnExpences_File_TypeChanging(value);
					this.SendPropertyChanging();
					this._Expences_File_Type = value;
					this.SendPropertyChanged("Expences_File_Type");
					this.OnExpences_File_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_User_Permission")]
	public partial class Table_User_Permission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_ID;
		
		private string _User_Name;
		
		private string _User_Email;
		
		private string _User_Password;
		
		private string _User_Type;
		
		private System.Nullable<bool> _New_Patient;
		
		private System.Nullable<bool> _Patients_Manegment;
		
		private System.Nullable<bool> _New_User;
		
		private System.Nullable<bool> _User_Manegment;
		
		private System.Nullable<bool> _Income;
		
		private System.Nullable<bool> _Spending;
		
		private System.Nullable<bool> _Earn;
		
		private System.Nullable<bool> _Backup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IDChanging(int value);
    partial void OnUser_IDChanged();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    partial void OnUser_EmailChanging(string value);
    partial void OnUser_EmailChanged();
    partial void OnUser_PasswordChanging(string value);
    partial void OnUser_PasswordChanged();
    partial void OnUser_TypeChanging(string value);
    partial void OnUser_TypeChanged();
    partial void OnNew_PatientChanging(System.Nullable<bool> value);
    partial void OnNew_PatientChanged();
    partial void OnPatients_ManegmentChanging(System.Nullable<bool> value);
    partial void OnPatients_ManegmentChanged();
    partial void OnNew_UserChanging(System.Nullable<bool> value);
    partial void OnNew_UserChanged();
    partial void OnUser_ManegmentChanging(System.Nullable<bool> value);
    partial void OnUser_ManegmentChanged();
    partial void OnIncomeChanging(System.Nullable<bool> value);
    partial void OnIncomeChanged();
    partial void OnSpendingChanging(System.Nullable<bool> value);
    partial void OnSpendingChanged();
    partial void OnEarnChanging(System.Nullable<bool> value);
    partial void OnEarnChanged();
    partial void OnBackupChanging(System.Nullable<bool> value);
    partial void OnBackupChanged();
    #endregion
		
		public Table_User_Permission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_Name
		{
			get
			{
				return this._User_Name;
			}
			set
			{
				if ((this._User_Name != value))
				{
					this.OnUser_NameChanging(value);
					this.SendPropertyChanging();
					this._User_Name = value;
					this.SendPropertyChanged("User_Name");
					this.OnUser_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_Email
		{
			get
			{
				return this._User_Email;
			}
			set
			{
				if ((this._User_Email != value))
				{
					this.OnUser_EmailChanging(value);
					this.SendPropertyChanging();
					this._User_Email = value;
					this.SendPropertyChanged("User_Email");
					this.OnUser_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_Password
		{
			get
			{
				return this._User_Password;
			}
			set
			{
				if ((this._User_Password != value))
				{
					this.OnUser_PasswordChanging(value);
					this.SendPropertyChanging();
					this._User_Password = value;
					this.SendPropertyChanged("User_Password");
					this.OnUser_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Type", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string User_Type
		{
			get
			{
				return this._User_Type;
			}
			set
			{
				if ((this._User_Type != value))
				{
					this.OnUser_TypeChanging(value);
					this.SendPropertyChanging();
					this._User_Type = value;
					this.SendPropertyChanged("User_Type");
					this.OnUser_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Patient", DbType="Bit")]
		public System.Nullable<bool> New_Patient
		{
			get
			{
				return this._New_Patient;
			}
			set
			{
				if ((this._New_Patient != value))
				{
					this.OnNew_PatientChanging(value);
					this.SendPropertyChanging();
					this._New_Patient = value;
					this.SendPropertyChanged("New_Patient");
					this.OnNew_PatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patients_Manegment", DbType="Bit")]
		public System.Nullable<bool> Patients_Manegment
		{
			get
			{
				return this._Patients_Manegment;
			}
			set
			{
				if ((this._Patients_Manegment != value))
				{
					this.OnPatients_ManegmentChanging(value);
					this.SendPropertyChanging();
					this._Patients_Manegment = value;
					this.SendPropertyChanged("Patients_Manegment");
					this.OnPatients_ManegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_User", DbType="Bit")]
		public System.Nullable<bool> New_User
		{
			get
			{
				return this._New_User;
			}
			set
			{
				if ((this._New_User != value))
				{
					this.OnNew_UserChanging(value);
					this.SendPropertyChanging();
					this._New_User = value;
					this.SendPropertyChanged("New_User");
					this.OnNew_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Manegment", DbType="Bit")]
		public System.Nullable<bool> User_Manegment
		{
			get
			{
				return this._User_Manegment;
			}
			set
			{
				if ((this._User_Manegment != value))
				{
					this.OnUser_ManegmentChanging(value);
					this.SendPropertyChanging();
					this._User_Manegment = value;
					this.SendPropertyChanged("User_Manegment");
					this.OnUser_ManegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Income", DbType="Bit")]
		public System.Nullable<bool> Income
		{
			get
			{
				return this._Income;
			}
			set
			{
				if ((this._Income != value))
				{
					this.OnIncomeChanging(value);
					this.SendPropertyChanging();
					this._Income = value;
					this.SendPropertyChanged("Income");
					this.OnIncomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spending", DbType="Bit")]
		public System.Nullable<bool> Spending
		{
			get
			{
				return this._Spending;
			}
			set
			{
				if ((this._Spending != value))
				{
					this.OnSpendingChanging(value);
					this.SendPropertyChanging();
					this._Spending = value;
					this.SendPropertyChanged("Spending");
					this.OnSpendingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Earn", DbType="Bit")]
		public System.Nullable<bool> Earn
		{
			get
			{
				return this._Earn;
			}
			set
			{
				if ((this._Earn != value))
				{
					this.OnEarnChanging(value);
					this.SendPropertyChanging();
					this._Earn = value;
					this.SendPropertyChanged("Earn");
					this.OnEarnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Backup]", Storage="_Backup", DbType="Bit")]
		public System.Nullable<bool> Backup
		{
			get
			{
				return this._Backup;
			}
			set
			{
				if ((this._Backup != value))
				{
					this.OnBackupChanging(value);
					this.SendPropertyChanging();
					this._Backup = value;
					this.SendPropertyChanged("Backup");
					this.OnBackupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
